#!/usr/bin/env bash

KERNEL_VERSION="7.2"

HARDENED_PATCH_VERSION="v${KERNEL_VERSION}-hardened1"

KERNEL_URL="https://cdn.kernel.org/pub/linux/kernel/v7.x/linux-${KERNEL_VERSION}.tar.xz"

KERNEL_SHASUM_URL="https://cdn.kernel.org/pub/linux/kernel/v7.x/sha256sums.asc"

PATCH_URL="https://github.com/anthraxx/linux-hardened/releases/download/${HARDENED_PATCH_VERSION}/linux-hardened-${HARDENED_PATCH_VERSION}.patch"

PATCH_SIG_URL="https://github.com/anthraxx/linux-hardened/releases/download/${HARDENED_PATCH_VERSION}/linux-hardened-${HARDENED_PATCH_VERSION}.patch.sig"

