hostonly="yes"
hostonly_cmdline="yes"
compress="zstd"
do_strip="yes"
aggressive_strip="yes"
do_hardlink="yes"
omit_dracutmodules+=" network nfs iscsi fcoe ceph rbd floppy parport_pc lp ppdev bluetooth 6lowpan firewire_core i2c_piix4 mfd_core mmc_core "
install_optional_items+=" "
