BOOLS_ON=(
        deny_bluetooth
        deny_ptrace
        secure_mode
        user_t_run_containers
)

BOOLS_OFF=(
        xguest_mount_media
        xguest_exec_content
        virt_use_usb
        virt_sandbox_use_all_caps
        virt_sandbox_use_audit
        spamd_enable_home_dirs
        selinuxuser_ping
        cron_userdomain_transition
        screen_allow_session_sharing
        postgresql_selinux_users_ddl
        postgresql_selinux_unconfined_dbadm
        postfix_local_write_mail_spool
        openvpn_enable_homedirs
        secadm_exec_content
        privoxy_connect_any
        auditadm_exec_content
        virt_use_nfs
        openvpn_can_network_connect
        openfortivpn_can_network_connect
        nscd_use_shm
        nfs_export_all_rw
        xend_run_blktap
        xguest_connect_network
        virtqemud_use_execmem
        use_virtualbox
        unconfined_mozilla_plugin_transition
        unconfined_chrome_sandbox_transition
        telepathy_tcp_connect_generic_network_ports
        staff_exec_content
        squid_connect_any
        nfs_export_all_ro
        xend_run_qemu
        named_write_master_zones
        mozilla_plugin_can_network_connect
        kerberos_enabled
        httpd_enable_cgi
        httpd_builtin_scripting
        guest_exec_content
        gssd_read_tmp
        gluster_export_all_rw
        dbadm_exec_content
        boinc_execmem
        xguest_use_bluetooth
)
