DWL_BUILD_PACKAGES=(
    libinput-devel
    wayland-devel
    libxkbcommon-devel
    wayland-protocols-devel
    pkg-config
    make
    gcc
    wlroots0.19-devel
    git
)

DWL_RUNTIME_PACKAGES=(
    libinput
    libxkbcommon
    mesa-libEGL
    libwayland-server
    libglvnd-gles
    wlroots0.19
)
