#!/usr/bin/env bash

KERNEL_BUILD_PACKAGES=(
    gcc
    make
    binutils
    flex
    bison
    ncurses-devel
    elfutils-libelf-devel
    openssl-devel
    gzip
    xz
    patch
    bc
    gnupg2
    binutils
    systemd-boot-unsigned
    openssl
)

KERNEL_BUILD_REMOVE_PACKAGES=(
    gcc
    make
    binutils
    flex
    bison
    ncurses-devel
    elfutils-libelf-devel
    openssl-devel
    dwarves
    patch
    bc
    openssh*
    less*
    parted
    elfutils-debuginfod-client
    binutils
    systemd-boot-unsigned
    openssl
)
