PW_BUILD_PACKAGES=(
  gcc
  gcc-c++
  meson
  ninja-build
  cmake
  pkgconf-pkg-config
  glib2-devel
  systemd-devel
  alsa-lib-devel
  libudev-devel
  libselinux-devel
  lua-devel
  pulseaudio-libs-devel
)

PW_RUNTIME_PACKAGES=(
  glib2
  alsa-lib
  pulseaudio-libs
  libselinux
)

