WLR_BUILD_PACKAGES=(
  meson
  ninja-build
  gcc-c++
  libdrm-devel
  libinput-devel
  mesa-libgbm-devel
  pixman-devel
  wayland-devel
  wayland-protocols-devel
  libxkbcommon-devel
  libseat-devel
  libglvnd-devel
  hwdata-devel
  libdisplay-info-devel
  libliftoff-devel
  vulkan-loader-devel
  vulkan-headers
)

WLR_RUNTIME_PACKAGES=(
  libdrm
  libinput
  mesa-libgbm
  pixman 
  libxkbcommon
  libseat
  libglvnd
  hwdata
  libdisplay-info
  libliftoff
)
